spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data-base-test
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
